language: node_js
node_js:
  - "node"
env:
  HUGO=0.54.0
  URL=https://github.com/gohugoio/hugo/releases/download
  PATH=/home/travis/build/ajizkai/blog:$PATH
install:
  - npm install
script:
  - curl -L "${URL}/v${HUGO}/hugo_${HUGO}_Linux-64bit.tar.gz" | gunzip | tar xvf -
  - npm run test
  - npm run cek
  - npm run build
  - npm run preview
  - npm run deploy
