language: node_js
node_js:
  - "node"
env:
  HUGO=0.54.0
  URL=https://github.com/gohugoio/hugo/releases/download
install:
  - npm install
script:
  - pwd
  - npm run cek
  - mkdir hugo
  - cd hugo
  - curl -L "${URL}/v${HUGO}/hugo_${HUGO}_Linux-64bit.tar.gz" | gunzip | tar xvf -
  - cd ..
  - ./hugo/hugo
  - npm run deploy
